# version: '3.8'

services:
  frontend:
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_HOST=192.168.4.62
    image: temp-monitor-frontend-i
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
  api:
    container_name: temp-monitor-api
    networks:
      - backend
    environment:
      - POSTGRES_HOST=temp-monitor-db
      - POSTGRES_PORT=5432
    image: "temp-monitor-api-i"
    restart: always
    ports:
      - "8081:8081"
  temp-monitor-db:
    image: "postgres:14"
    container_name: temp-monitor-db
    hostname: temp-monitor-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: temp-monitor-db
    ports:
      - "5432:5432"
    volumes:
      - ./api/db/sql_scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
networks:
  backend:
    driver: bridge
  